# Generated by Django 5.0 on 2024-01-14 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaborDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(max_length=100)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimum_exec_time', models.DurationField()),
                ('standard_exec_time', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_of_measurement', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.labordifficulty')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.labor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='labors',
            field=models.ManyToManyField(through='product_management.ProductLabor', to='product_management.labor'),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(through='product_management.ProductOption', to='product_management.option'),
        ),
        migrations.CreateModel(
            name='ProductRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.rawmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(through='product_management.ProductRawMaterial', to='product_management.rawmaterial'),
        ),
    ]
