# Generated by Django 5.0 on 2024-01-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_unitofmeasurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
