# Generated by Django 5.0 on 2024-01-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_labor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlabor',
            name='execution_time',
        ),
        migrations.AlterField(
            model_name='labor',
            name='execution_time',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_exec_time',
            field=models.DecimalField(decimal_places=2, help_text='Duration in days', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_exec_time',
            field=models.DecimalField(decimal_places=2, help_text='Duration in days', max_digits=5),
        ),
    ]
