# Generated by Django 5.0 on 2024-01-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='labordifficulty',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, help_text='Price per hour in your local currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per option', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_exec_time',
            field=models.DecimalField(decimal_places=2, help_text='Minimum execution time in days', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_exec_time',
            field=models.DecimalField(decimal_places=2, help_text='Standard execution time in days', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of raw material', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit of measurement', max_digits=10),
        ),
    ]
