# Generated by Django 5.0 on 2024-01-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labordifficulty',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
