# Generated by Django 5.0 on 2024-01-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0007_alter_labordifficulty_price_per_hour_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_pacient', models.CharField(max_length=255)),
                ('data_intrare', models.DateTimeField(auto_now_add=True)),
                ('termen', models.DateField(blank=True, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=50)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.clinicprofile')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.doctorprofile')),
                ('lucrare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
                ('optiuni', models.ManyToManyField(blank=True, to='product_management.option')),
            ],
        ),
    ]
