# Generated by Django 5.0 on 2024-01-14 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
        ('product_management', '0007_alter_labordifficulty_price_per_hour_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='urgent',
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarii'),
        ),
        migrations.AlterField(
            model_name='order',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.clinicprofile', verbose_name='Clinica'),
        ),
        migrations.AlterField(
            model_name='order',
            name='data_intrare',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Intrare'),
        ),
        migrations.AlterField(
            model_name='order',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.doctorprofile', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lucrare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product', verbose_name='Lucrare'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nume_pacient',
            field=models.CharField(max_length=255, verbose_name='Nume Pacient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='optiuni',
            field=models.ManyToManyField(to='product_management.option', verbose_name='Optiuni'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='termen',
            field=models.DateField(verbose_name='Termen'),
        ),
    ]
