# Generated by Django 5.0 on 2024-01-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_remove_order_urgent_order_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_intrare',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Intrare'),
        ),
    ]
