# Generated by Django 5.0 on 2024-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_alter_order_data_intrare'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_due_date_adjustable',
            field=models.BooleanField(default=False, verbose_name='Adjust Due Date?'),
        ),
    ]
