# Generated by Django 5.0 on 2024-01-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_order_is_due_date_adjustable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_due_date_adjustable',
            field=models.BooleanField(default=False, verbose_name='Urgent?'),
        ),
    ]
