# Generated by Django 5.0 on 2024-01-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_remove_order_is_due_date_adjustable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
        migrations.AddField(
            model_name='order',
            name='urgent_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Urgent Due Date'),
        ),
    ]
